name: Publish package

on:
  push:
    tags: ['*']
  workflow_dispatch:
permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use nodejs
        uses: actions/setup-node@v6
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - run: npm ci
      - name: Publish
        run: npm publish --access public
